### ISSUE TITLE
Objectives for 2024.

### ISSUE THREAD

**Issue by righettod** [OWASP/www-project-secure-headers#200]
# 🔵TODO

None

# 🟡Pending by the OSHP team

None

# 🟠Pending by a third party

None

# 🟢Done

- [x] Find a solution for the question https://github.com/oshp/oshp-tracking/discussions/29
- [x] Submit an application to upgrade to **[production](https://owasp.org/www-committee-project/index.html#div-promotions)** status.
- [x] Review the configuration proposed for the header `Permissions-Policy` to keep it up to date.
- [x] Add clarification to indicate to set the header `Clear-Site-Data` on logout endpoint.
- [x] Submit an application for a podcast in french at https://www.nolimitsecu.fr
- [x] Handle https://github.com/oshp/oshp-tracking/issues/19
- [x] Handle https://github.com/oshp/oshp-tracking/issues/28 
- [x] Add a section, into the best practices area, about how to prevent sensitive information exposure due to caching (use same approach than for CORS but with cache headers).
  * https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
  * https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching

# 🔴Cancelled

- [x] Handle https://github.com/oshp/oshp-tracking/issues/11
